# This is a basic workflow to help you get started with Actions

name: Codecov

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    #- name: Coveralls Github Action
    #  uses: coverallsapp/github-action@1.1.3
    #  with:
    #    github-token: ${{ secrets.GITHUB_TOKEN }}
    #    path-to-lcov: ./coverage/lcov.info
    #  run: coveralls --service=github
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    path-to-lcov: ../../coverage/lcov.info
    #- name: Generate coverage report
    #  run: |
    #    pip install pytest
    #    pip install pytest-cov
    #    pytest --cov=./ --cov-report=xml
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
        
